name: Monday and Thursday Posts

on:
  schedule:
    # Run every Monday and Thursday at 6:00 AM UTC
    - cron: "0 6 * * 1,4"
  workflow_dispatch:  # Enable manual triggering

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Monday and Thursday posts
      env:
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
        TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
        TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
        TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
      run: python -m src.main --type daily

    - name: Ensure daily_state.yaml exists
      run: |
        if [ ! -f daily_state.yaml ]; then
          touch daily_state.yaml
          echo "{}" > daily_state.yaml
        fi

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add logs.txt
        if [ -f daily_state.yaml ]; then git add daily_state.yaml; fi
        git commit -m "Update daily state and logs after run" || echo "No changes to commit"
        git push
