# name: Ramadan Posts

# on:
#   schedule:
#     - cron: "0 22 * * 0-2,4-6"
#   workflow_dispatch:

# jobs:
#   post:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: pip install -r requirements.txt

#     - name: Run Ramadan posts
#       env:
#         FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
#         FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
#         TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
#         TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
#         TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
#         TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
#       working-directory: .
#       run: python -m src.main --type ramadan

#     - name: Commit changes
#       run: |
#         git config --global user.name "GitHub Actions"
#         git config --global user.email "actions@github.com"
#         git add post_state.yaml logs.txt
#         git commit -m "Update state and logs after run" || echo "No changes to commit"
#         git push
