name: Ramadan Posts

on:
  schedule:
    # Run every day at 12 PM UTC (adjust time as needed)
    - cron: "25 12 * * 0-4,6"  # Sunday (0) to Thursday (4), and Saturday (6)
  workflow_dispatch:  # Enable manual triggering

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Ramadan posts
      env:
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
        TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
        TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
        TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
      run: python src/main.py --type ramadan

    - name: Commit state changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add post_state.yaml
        git commit -m "Update post state after run" || echo "No changes to commit"
        git push
